name: volkhov_maps_app
description: A new Flutter application starter.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  bloc: ^8.1.1
  cupertino_icons: ^1.0.3
  device_info_plus: ^4.0.1
  easy_localization: ^3.0.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^7.0.1
  flutter_svg: ^1.1.6
  flutter_udid: ^2.0.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  geolocator: ^9.0.2
  google_fonts: 2.1.0
  google_maps_cluster_manager: ^3.0.0+1
  google_maps_flutter: ^2.2.3
  google_maps_flutter_web: ^0.4.0+5
  logging: ^1.0.2
  package_info: ^2.0.2
  path_provider: ^2.0.9
  provider: ^6.0.2
  sembast: 3.1.2
  sembast_web: ^2.0.1+1
  shared_preferences: ^2.0.13

dev_dependencies:
  build_runner: ^2.1.4
  flutter_lints: null
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/i18n/
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/

  # Example of setting up custom fonts
  fonts:
    - family: SFUIDisplay
      fonts:
        - asset: assets/fonts/SFUIDisplay-Ultralight.ttf
          weight: 100
        - asset: assets/fonts/SFUIDisplay-Thin.ttf
          weight: 200
        - asset: assets/fonts/SFUIDisplay-Light.ttf
          weight: 300
        - asset: assets/fonts/SFUIDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFUIDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/SFUIDisplay-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SFUIDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/SFUIDisplay-Heavy.ttf
          weight: 800
        - asset: assets/fonts/SFUIDisplay-Black.ttf
          weight: 900
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
